config/routes.rb
Rails.application.routes.draw do
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'login' => 'sessions#new', :as => 'login'
  get 'signup' => 'users#new', :as => 'signup' 
  
  resources :users
  resources :cards
  resources :sessions
  resources :decks do
    post 'set_current', on: :member
  end
  
  root 'home#index', as: :home
  post 'check_translation', to: 'home#check_translation'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
  belongs_to :user

  mount_uploader :flashpicture, FlashpictureUploader

  validates :user_id, presence: true
  validates :deck_id, presence: true
  validates :original_text, presence: true
  validate :equality_test, on: :create
  validates :translated_text, presence: true
  before_create :set_the_date

  def equality_test
    errors.add(:original_text, "Original can't be equal to translated") if self.original_text.downcase.strip == self.translated_text.downcase.strip
  end

  scope :unreviewed, -> { where('review_date <= ?', DateTime.now).order('RANDOM()') }

  protected
  def set_the_date
    self.review_date = DateTime.now
  end
    
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
  belongs_to :user

  validates :title, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :decks
  has_many :cards

  validates_confirmation_of :password
  validates :password, presence: true, on: :create
  validates :email, presence: true, uniqueness: true

  def current_deck
    decks.where(current: true).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def not_authenticated
    redirect_to login_url, :alert => 'First login to access this page.'
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :fetch_card, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  def index
    @cards = current_user.cards.all
  end

  def show
    @user = current_user
  end

  def new
    @card = current_user.cards.new
  end

  def edit
  end

  def create
    @card = current_user.cards.new(card_params)
    if card_params[:remote_flashpicture_url]
      @card.remote_flashpicture_url = card_params[:remote_flashpicture_url]
    end
    if @card.save!
      redirect_to cards_path
    else
      render :new
    end
  end

  def update
    if @card.update!(card_params)
      redirect_to cards_path
    else
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private
  
  def fetch_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:review_date, :original_text, :translated_text, :user_id, :deck_id, :flashpicture, :remote_flashpicture_url)
  end


end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]
  before_action :require_login

  def index
    @decks = current_user.decks.all
  end

  def show
    @cards = @deck.cards
  end

  def new
    @deck = current_user.decks.new
  end

  def edit
  end

  def create
    @deck = current_user.decks.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_current
    result = SetCurrentDeck.call(
      id: params[:id],
      user: current_user
    )
    redirect_to decks_path, notice: result.notice
  end

  private
    def set_deck
      @deck = current_user.decks.find(params[:id])
    end

    def deck_params
      params.require(:deck).permit(:title, :user_id)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_login
  
  def index
    if current_user.current_deck
      @card = current_user.current_deck.cards.unreviewed.first
    else
      @card = current_user.cards.unreviewed.first
    end
  end

  def check_translation
    result = CheckTranslation.call(
    answer: params[:answer],
    id: params[:id]
    )
    redirect_to home_path, notice: result.notice
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    user = login(params[:email], params[:password])
    if user
      redirect_back_or_to home_url, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    logout
    redirect_to home_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      auto_login(@user)
      redirect_back_or_to home_url
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update!(user_params)
      redirect_to home_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for (@card), :html => {:multipart => true} do |f| %>
    <%= f.hidden_field :user_id %>
    <%= f.collection_select :deck_id, current_user.decks.order(:title), :id, :title%>
    <%= f.text_field :original_text, placeholder: 'Original Text' %>
    <%= f.text_field :translated_text, placeholder: 'Translated Text' %>
    <%= f.text_field :review_date, placeholder: 'Review Date'%>
    <div>
      <strong>Choose picture associated to card: </strong>
    </div>
    <div>
      <%= f.file_field :flashpicture %>
      <%= f.label :remote_flashpicture_url, "or image URL" %>
      <%= f.text_field :remote_flashpicture_url %>
      <%= f.button :submit, disabled: current_user.decks.order(:title).empty? %>
    </div>
<% end %>

app/views/cards/edit.html.erb
<%= render partial: "form" %>

app/views/cards/index.html.erb
<% @cards.each do |card| %>
  <div>
    <strong>User ID</strong>: <%= card.user_id %>
    <strong>Deck ID</strong>: <%= card.deck_id %>
    <strong>Original</strong>: <%= card.original_text %>
    <strong>Translated</strong>: <%= card.translated_text %>
  </div>
    <div>
      <%= card.review_date %>
   </div>
  <%= link_to 'Delete', card_path(card), method: :delete %>
  <%= link_to 'Edit', edit_card_path(card) %>
  <%= link_to 'Show', card_path(card) %>
  <hr>
<% end %>

app/views/cards/new.html.erb
<%= render partial: "form" %>

app/views/cards/show.html.erb
<%= image_tag @card.flashpicture_url(:thumb).to_s %>
<div><strong>Original Text: </strong><%= @card.original_text %></div>
<div><strong>Translated Text: </strong><%= @card.translated_text %></div>

app/views/decks/_form.html.erb
<%= simple_form_for(@deck) do |f| %>
  <%= f.error_notification %>

  <%= f.hidden_field :user_id %>

  <div class="form-inputs">
    <%= f.text_field :title, placeholder: 'Title' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing Deck</h1>

<%= render 'form', deck: @deck %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Decks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <%= form_tag set_current_deck_path(deck.id) do %>
        <tr>
          <td><%= deck.title %></td>
          <td><%= link_to 'Show', deck %></td>
          <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
          <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= hidden_field_tag 'id', deck.id %></td>
          <td><%= hidden_field_tag 'user_id', current_user.id %></td>
          <td><%= submit_tag 'Set current', name: 'Submit' %></td>
        </tr>
      <% end %>
  <% end %>
  <%= link_to 'New Deck', new_deck_path %>
  </tbody>
</table>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form', deck: @deck %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<%= @deck.title %>
<% @cards.each do |card| %>
  <div><%= card.original_text %></div>
<% end %>

<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>

app/views/home/index.html.erb
<p> Первый в мире удобный менеджер флеш-карточек. Именно так.</p>
<% if @card.present? %>
  <%= form_tag check_translation_path do %>
    <%= image_tag @card.flashpicture_url(:thumb).to_s if @card.flashpicture? %>
    <div><%= @card.translated_text %></div>
    <%= hidden_field_tag 'id', @card.id %>
    <%= text_field_tag 'answer', nil, placeholder: "Your translate" %>
    <%= submit_tag "Check!", name: 'Submit' %>
  <% end %>
<% else %>
  <div>"Gratz! Rest a little, cuz cards not found!"</div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Флэшкарточкер</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
</head>
<body>
<section id="container">

  <header class="clearfix">
    <div><h1>Флэшкарточкер</h1></div>
    <ul class="navigation-links">
      <li><%= link_to 'Все карточки', cards_path %> </li>
      <li><%= link_to 'Добавить карточку',  new_card_path %></li>
      <li><%= link_to 'Колоды',  decks_path %></li>
    </ul>

    <% if current_user %>
        <div>
          <div>Logged in as <%= current_user.email %>.</div>
          <% if current_user.current_deck %>
            <div>Current deck is <%= current_user.current_deck.title %></div>
          <% else %>
            <div> Current deck is not selected </div>
          <% end %>
          <div><%= link_to 'Настройки пользователя',  edit_user_path(current_user) %></div>
          <div><%= link_to 'Log out', logout_path %></div>
        </div>
    <% else %>
        <div>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "log in", login_path %>.
        </div>
    <% end %>
  </header>

  <%= yield %>
  <%= render partial: "shared/flash_messages" %>

</section>
</body>

</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class='error-messages'>
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class='field'>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class='field'>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render partial: 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>